### ISSUE TITLE
Create generators for tests

### ISSUE THREAD

**Issue by kotp** [exercism/perl5#135]
This will have the advantage of directly using the canonical data in [x-common](https://github.com/exercism/x-common).

An example of doing this can be found with the Go and Ruby tracks.

[Go executable](https://github.com/exercism/xgo/blob/master/gen/gen.go)
[Go test helper](https://github.com/exercism/xgo/blob/master/bin/test-without-stubs)

[ruby generate executable](https://github.com/exercism/xruby/blob/master/bin/generate)
[ruby generate library](https://github.com/exercism/xruby/blob/master/lib/generator.rb)
[Sample test cases handler](https://github.com/exercism/xruby/blob/master/lib/hello_world_cases.rb)

**Comment by mienaikage** [comment]
I might look into porting the generator from https://github.com/exercism/xperl6

**Comment by mienaikage** [comment]
Generator in PR https://github.com/exercism/xperl5/pull/148
