### ISSUE TITLE
Update installation docs

### ISSUE THREAD

**Issue by NobbZ** [exercism/perl5#147]
Today in the [exercism/support gitter](gitter.im/exercism/support) there was an error message reported about `Test/More.pm` not found.

He used a minimal and plain [`centos:7`](https://hub.docker.com/_/centos/) inside a Docker-container. He did not install anything further, because documentation of the track states that everything should be fine on linux.

Further research on this topic discovered, that in fact, `perl` itself is preinstalled on CentOS, because its needed internally. Perhaps even because it were needed if one wants to rebuild the Kernel?

Anyway, `Test::More` is **not** bundled with `perl` in Fedora and CentOS, one needs to `yum install perl-Test-Simple` there. On other RPM based distributions `Test::More` seems to be included in `perl`, see rpmfind: https://www.rpmfind.net/linux/rpm2html/search.php?query=perl(Test%3A%3AMore)

Nevertheless, as we have found at least 1 major distributions where the current docs of "no need to install anything" do not hold, I think they should be re-evaluated and the majors should be written out explicitely, ala:

* CentOS and Fedora: install `perl-Test-Simple` additionally
* Ubuntu and Debian: no need to install anything further (_This is an unverified assumption to make explicitness of the table clear_)

**Comment by NobbZ** [comment]
Addition: Even if `perl` is probably available and a core dependency of most linux distributions, I think we should make sure to list the actual packages anyway, and if it is just to mark them as manually installed instead of beeing installed as a dependency (which by its nature may vanish at any time when other packages are uninstalled).

**Comment by mienaikage** [comment]
I may edit the docs to suggest using [plenv](https://github.com/tokuhirom/plenv) so users can have a version of Perl installed and set locally to their exercism directory.

**Comment by NobbZ** [comment]
I do not like to require any kind of version manager unless technically
necessary. Packages are available and should be therefore preferred. Adding
another layer of package management often brings more trouble than
necessary. I think though they can be suggested in a kind of further read
or if you know what you are doing.

Daniel Mita <notifications@github.com> schrieb am Do., 15. Juni 2017, 10:53:

**Comment by mienaikage** [comment]
Ah I see now. I don't know much about Fedora-based distros, but it turns out that they intentionally don't include all of the core modules.

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Developer_Guide/lib.details.html#libraries.perl

Perhaps add an instruction for Fedora/Red Hat/CentOS that they should also install `perl-core` would be the best solution.

**Comment by mienaikage** [comment]
Updates in https://github.com/exercism/xperl5/pull/152

**Comment by mienaikage** [comment]
Closing this as https://github.com/exercism/perl5/pull/152 has now been merged.
