### ISSUE TITLE
tests don't run under Perl 5.26

### ISSUE THREAD

**Issue by schmonz** [exercism/perl5#178]
Hi!

As of Perl 5.26 (May 2017), `.` is no longer on the default module include path. As a result, tests like this one:

```perl
eval "use $module";
ok !$@, "Cannot load $module"
    or BAIL_OUT "Cannot load $module; Does it compile? Does it end with 1;?";
```

all fail. I ran into this just now during an interview. If I hadn't known about the 5.26 change, I'm not sure how much more time we would have lost trying to figure this out.

For my interview, I just prepended this to the one test file I was working with:

```perl
push @INC, '.';
```

This is one of the options listed here: http://blogs.perl.org/users/sawyer_x/2017/05/perl-5260-is-now-available.html

Until this is fixed, it will be difficult for Perl newbies using the latest released Perl to get through any of the exercises.

**Comment by mienaikage** [comment]
Thanks for the info. A handful of exercises are using FindBin, but unfortunately I have yet to get round to updating them all, and wasn't aware this was an issue.

I'll see if I can put together a quick fix to resolve this.

**Comment by mienaikage** [comment]
Do you know which exercise you were on when you ran into this issue?

**Comment by schmonz** [comment]
I was doing SpaceAge.

**Comment by mienaikage** [comment]
I've fetched the exercise and put the very bare bones for a package together, but I don't seem to be having the same issue:

```$ perl -v

This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-multi
(with 1 registered patch, see perl -V for more detail)

Copyright 1987-2017, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

$ cat SpaceAge.pm
package SpaceAge;

1;

$ prove . -v
./space.t .. 
1..20
ok 1 - Missing SpaceAge.pm
ok 2 - Cannot load SpaceAge
not ok 3 - SpaceAge->can('new')
Bailout called.  Further testing stopped:  Missing package SpaceAge; or missing sub new()
Bail out!  Missing package SpaceAge; or missing sub new()

#   Failed test 'SpaceAge->can('new')'
#   at ./space.t line 22.
#     SpaceAge->can('new') failed
FAILED--Further testing stopped: Missing package SpaceAge; or missing sub new()
```
The test suite is using [FindBin](https://metacpan.org/pod/FindBin). Could you possibly put the files you have in a pastebin?

**Comment by schmonz** [comment]
It may be that I ran `exercism fetch perl5` a while ago and space-age was downloaded then. In which case a fresh fetch wouldn't have had this problem. Just in case, here are the files I'm working with (including my partial solution to the exercise):

https://gist.github.com/schmonz/ea973425f277fc30398538917b3f61ca

If SpaceAge has been fine for a while, I'd be happy for a quick double-check that all the exercises are now using FindBin, and then to have this report closed. :-)

**Comment by mienaikage** [comment]
Apparently I did put FindBin in all the exercises, I'd just forgotten 😳

https://github.com/exercism/perl5/pull/126
