### ISSUE TITLE
Twelve-days is out of sync with specification

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/perl5#237]
The specification for the twelve days exercise [has changed](https://github.com/exercism/problem-specifications/pull/1329/files) and the Perl 5 implementation needs to be updated.

**Comment by mienaikage** [comment]
I had planned to make changes to all of the exercises to allow the generator to update canonical data automatically, but unfortunately haven't done so yet due to lack of time. It would be ideal if changes could be made to this exercise so that the generator can take care of this for us.
