### ISSUE TITLE
Track is missing introduction

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/perl5#271]
The [track page](https://exercism.io/my/tracks/perl5) is showing the "TODO" text underneath the track title because no introduction has been added.

**Comment by rfilipo** [comment]
PR #275 has an update in config.json solving this issue.

**Comment by kytrinyx** [comment]
@rfilipo For future reference, if you put "Closes #275" in the body of a PR then when the PR gets merged to master, the original issue will automatically get closed.

https://help.github.com/en/articles/closing-issues-using-keywords
