### ISSUE TITLE
How to run a specific test case

### ISSUE THREAD

**Issue by szTheory** [exercism/perl5#345]
How do you run a specific test case? I want to fix a single broken test, but since they are all defined in a __DATA__ hash at the bottom I don't know how to narrow it down. It's hard to debug a specific test if you have to run the entire suite at once and get flooded with output. The best I can figure out is to copy the test to a new file, and delete every test except for the one you want to run, but it's tedious to do this each time, and hard to chop up the JSON without getting parse errors. So I'm wondering if I'm missing something obvious. I don't see anything about it in the [test instructions on Exercism](https://exercism.io/tracks/perl5/tests).

**Comment by mienaikage** [comment]
Is this an issue with a particular exercise? When running `prove .` the failing tests should be the most prominent information given. Are you using the verbose flag? (`-v`)

```
# Failed test 'Say Hi!'
# at exercises/hello-world/hello-world.t line 15.
# +---------+---------------+
# | GOT     | CHECK         |
# +---------+---------------+
# | <UNDEF> | Hello, World! |
# +---------+---------------+
```

The first line indicates which test failed. Usually the quoted string after `Failed test` should be telling you which case failed.

**Comment by mienaikage** [comment]
A potential approach you could take is setting the `PERL5OPT` environment variable to load the [Test2::Plugin::BailOnFail](https://metacpan.org/pod/Test2::Plugin::BailOnFail) module. This will cause the tests to cease once it encounters its first failure.

For example: `PERL5OPT=-MTest2::Plugin::BailOnFail prove .`

It would be useful to know what command you're running, the exercise you're working on, and the output you're getting to see how this can be improved.
