### ISSUE TITLE
 AllYourBase.pm can't work, may be too complex.

### ISSUE THREAD

**Issue by mhhai** [exercism/perl5#444]
Can you release a useful and simple version of AllYourBase.pm.

**Comment by kotp** [comment]
Can you show `AllYourBase.pm` so that we can see what you are referring to?

So that we can figure out what the details are that may be actionable?

**Comment by m-dango** [comment]
The solution in .meta was using a hack to check the tests. I've implemented a proper solution confirming that the exercise does work correctly in https://github.com/exercism/perl5/pull/449.

**Comment by mhhai** [comment]
Hi, it's working now, thanks. I mean before that it is better not to call QuickSolve.pm to execute.

**Comment by kotp** [comment]
Closing because `Quicksolve` is no longer used.
