### ISSUE TITLE
Contributor Guide link broken

### ISSUE THREAD

**Issue by thiago-glauco** [exercism/perl5#471]
The contributor guide link in the README file is broken. Please provide a new one.

[contributing guide](https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/README.md)

**Comment by m-dango** [comment]
This is likely what will be needed in its place: https://exercism.org/docs/building

**Comment by m-dango** [comment]
I forgot I already have a code review open to fix this: https://github.com/exercism/perl5/pull/469
