### ISSUE TITLE
[Simple Cipher, Robot Simulator, Linked List, Simple Linked List, Queen Attack, Pythagorean Triplet, Saddle Points] Tests pass, always

### ISSUE THREAD

**Issue by kareila** [exercism/perl5#532]
As I reported in the site forum, the test suite in the Perl 5 version of Simple Cipher is currently broken. All of the tests pass on any given input when using the online editor.

Link to discussion: http://forum.exercism.org/t/tests-in-perl-5-version-of-simple-cipher-seem-broken/4565/2

**Comment by kotp** [comment]
Thank you for reporting this.

**Comment by kareila** [comment]
I just discovered that Robot Simulator has the same problem.

**Comment by m-dango** [comment]
I'll look into updating these exercises to use the canonical test data next. Both of these exercises have sadly been neglected for quite some time.

**Comment by kareila** [comment]
I just discovered that Linked List has the same problem.

**Comment by MatthiasMuth** [comment]
I have the same problem in Queen Attack, too.
Thanks for help!

**Comment by kareila** [comment]
Adding Pythagorean Triplet to the list.

**Comment by kareila** [comment]
Adding Saddle Points to the list. I believe I've now checked every currently available exercise.

**Comment by MatthiasMuth** [comment]
I have noticed that all tests that show the symptom (tests in the editor succeed without actually running) have one thing in common:
They all use
`use Test2::Bundle::More;`
and they all contain calls like
`    ... or diag explain ...;`

All other exercises that I downloaded (I didn't download all, though) and that work correctly in the Exercism editor that I have checked use
`use Test2::V0;`
and none of them contains any calls to `explain` (with the exception of `list-ops`, which uses `Test2::Bundle::More`, but still does not use `explain`).
 
The thing is that `explain` used to be a member function of `Test::More`, but it is explicitly not contained in any of the `Test2` suites anymore. So if any test fails, the test produces a run time error for calling an unknown subroutine.
See explanations why `explain` is not in `Test2::Bundle::More` [here](https://metacpan.org/pod/Test2::Bundle::More#explain()).

Maybe this observation helps in closing in on the problem.

**Comment by m-dango** [comment]
I've created a PR for the new simple-cipher tests, which will require a solution: https://github.com/exercism/perl5/pull/535

**Comment by m-dango** [comment]
PR created for reimplementation of robot-simulator, requires solution: https://github.com/exercism/perl5/pull/536

**Comment by m-dango** [comment]
Reimplementation of queen-attack: https://github.com/exercism/perl5/pull/537

**Comment by m-dango** [comment]
Reimplementation of pythagorean-triplet: https://github.com/exercism/perl5/pull/538

**Comment by m-dango** [comment]
Reimplementation of saddle-points: https://github.com/exercism/perl5/pull/539

**Comment by habere-et-dispertire** [comment]
> Reimplementation of pythagorean-triplet: #538

<details>
<summary>perl solution 💜</summary>
<code>
##
# https://github.com/exercism/perl5/pull/538#issuecomment-1575584895
##
sub triplets_with_sum {
    my ($sum) = @_;
    my @solutions;
    for my $a ( 1 .. $sum ) {
        my $numerator   = 2*$a**2 + $sum**2 - 2*$sum*$a;
        my $denominator = 2*( $sum - $a );
        if ( $denominator > 0 and $numerator % $denominator == 0 ) {
            my $c = $numerator / $denominator;
            my $b = $sum - $a - $c;
            push @solutions, [ $a, $b, $c ] if $b > $a;
        }
    }
    return [ @solutions ];
}
</code>
</details>

**Comment by m-dango** [comment]
PRs are open to resolve all issues in here. I've marked `linked-list` and `simple-linked-list` as WIP as there are changes to be made to the track before these can be updated.
